# Generated by Django 2.2.6 on 2022-09-01 15:54

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220901_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Текст нового поста', validators=[posts.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
